create table if not exists partners
(
    partner_id    bigint generated by default as identity,
    created_at    timestamp default NOW(),
    deleted       boolean DEFAULT false,
    updated_at    timestamp default NOW(),
    email         varchar(255),
    phone         varchar(255),
    password      varchar(255),
    role          varchar(255),
    primary key (partner_id)
);

create table if not exists shops
(
    shop_id         bigint generated by default as identity,
    partner_id  bigint,
    created_at      timestamp default NOW(),
    updated_at      timestamp default NOW(),
    deleted       boolean DEFAULT false,
    address         varchar(255),
    address_detail  varchar(255),
    business_number varchar(255),
    close_at        varchar(8),
    contact         varchar(255),
    day_off         varchar(255),
    facilities      varchar(255),
    latitude        numeric,
    longitude       numeric,
    business_area    varchar(255),
    name            varchar(255),
    notice          varchar(255),
    open_at         varchar(8),
    scale           varchar(255),
    type           varchar(255),
    theme           varchar(255),
    manner         varchar(255),
    payment         varchar (255),
    how_to_come         varchar (255),
    home_care_area         varchar (255),
    zonecode         varchar (255),
    home_care_scale         varchar (255),
    etiquette         varchar (255),
    service_time         varchar (255),
    service_target         varchar (255),
    introduce         varchar (255),
    hit     integer,
    status  varchar(255),
    ad_status  varchar(255),
    reject_message  varchar(255),
    primary key (shop_id)
);

create table if not exists programs (
    program_id         bigint generated by default as identity,
    shop_id bigint,
    name    varchar(255),
    price   bigint,
    discounted_price    bigint,
    description varchar(2000),
    created_at    timestamp default NOW(),
    deleted       boolean DEFAULT false,
    updated_at    timestamp default NOW(),
    primary key (program_id)
);


create table if not exists therapists (
    therapist_id         bigint generated by default as identity,
    shop_id bigint,
    name varchar(255) ,
    position varchar(255) ,
    nationality varchar(255),
    description varchar (2000),
    created_at    timestamp default NOW(),
    deleted       boolean DEFAULT false,
    updated_at    timestamp default NOW(),
    primary key (therapist_id)
);


create table if not exists phone_verifications
(
    phone                    varchar(255),
    expired_at               timestamp,
    verification_code        integer,
    verified_at              timestamp,
    created_at               timestamp default NOW(),
    updated_at               timestamp default NOW(),
    primary key (phone)
);

create table if not exists email_verifications
(
    email_verification_id    bigint generated by default as identity,
    email_verification_token varchar(255),
    created_at               timestamp default NOW(),
    deleted                  boolean,
    updated_at               timestamp default NOW(),
    email                    varchar(255),
    expired_at               timestamp,
    verification_code        integer,
    verified_at              timestamp,
    primary key (email_verification_id)
);

create table if not exists admins
(
    admin_id    bigint generated by default as identity,
    login_id    varchar(255),
    name         varchar(255),
    password      varchar(255),
    role         varchar(255),
    created_at    timestamp default NOW(),
    deleted       boolean DEFAULT false,
    updated_at    timestamp default NOW(),
    primary key (admin_id)
);

create table if not exists shops_imgs
(
    shop_id         bigint,
    img_path       varchar(255),
    created_at    timestamp default NOW(),
    updated_at    timestamp default NOW(),
    deleted       boolean DEFAULT false,
    primary key (shop_id, img_path)
);
